#+TITLE Unknown

#+PROMPT 
I didn’t think I would ever fall in love again. I know that everyone says that after a heartbreak, but the difference is that I’m not heartbroken. I’m not cynical, or pessimistic, or sad. I’m
just someone who once felt something bigger than anything else I’d ever felt and when I lost it, I honestly believed I would never have that again. But... I was 22 then and life is long. And I’m
feeling things right now that I haven’t in a long, long time.

#+STORY 

I preferred sitting in the last row, almost always, except on occasions when the professor would take issue with the folks hiding in those nether regions and would promptly request them to occupy the
vacant ones in the front. I never understood the reason behind it, perhaps they would think that us people in the back were always upto some mischief of the disruptive kind, or may be they thought
their words and ideas would fall to no effect beyond the realms of the front row seats. But then again, when I look back now, any conspiracy of any nature was almost always seeded from these rows,
whether it be the plan to collectively bunk all the post-lunch classes on Friday, or the plot to claim attendance on behalf of an absentee student. However, I had my own odd reasons of sitting as far
as possible from the professors.

I loved to draw. I would draw pencil sketches, enacting storylines like a comic strip of my own. And somehow, sitting in that classroom did wonders to my palette of imagination, as I used to come up
with all sorts of stories panning across various walks of life. Some day, in the engineering chemistry lecture, I would create this mystic village on the edge of the world which would have plantations of bank notes,
while sometimes in the Basic Electronics lecture it would be a sketch of our hostel mess during the peak hours. So, in a sense, my sketches ranged from the real to the surreal, their narrative mostly
defined by the mood at that time or perhaps something that would have captured my imagination. There was no order or process to what I would sketch on any given day during any of those classes. Most
of the pages of my notebooks, whose ideal purpose would have been to take down notes from the chalkboard, were filled with drawings ranging from humanly decipherable ones to which even I couldn't make
any sense of. You could even say, it was a pure stream of conciousness when I put the pencil on the paper, my ears forever yearning for that dull rasping noise when the tip would graze the sheets.

I had read a whole lot of comic books in my childhood, and perhaps that might have had some effect on me, but even apart from that, drawing was largely the only tool at my disposal during all those
years wherein I could channel evrything inside into something substantial. I remember my parents proudly displaying some of the percievably good ones on the walls of the living room for all the guests
to see, and they loved to boast about how their son could sketch quite well without much of a training. But that was that. And when it was time to get serious about life, they, along with my
teachers and neighbors,somwhow felt I would make a better engineer than an artist. I didn't understand the world enough yet to have any opinion, and may be even I didn't take myself that seriously as an
artist.

So here I was, yet again, seated in my marked position where there was the wall to my left and several rows of seats decending beneath, ending at the narrow passgeway that separated the students'
territory from that of the faculty. Beyond the narrow passageway, would be the desk, chair and a lectern on a dias with the chalkboard in the back, devoid of any significance unless occupied by one of
the professors. To me, all of it, seemed less of a classroom and more like a medieval king's court wherein the monarch would pass down orders to those gathered in front of him. Come to
think of it, the lecture hall did seem like a cross section cut away from the ancient roman amphitheatre, except here the seat of power was reversed.

Anyways it was 8:05 am, and Professor Pandey was due any moment. I was in early, as usual, for the seats in the back are often in high demand for some specific faculty members, Mr. Pandey being one of
them. As soon as he walked in, a hush descended over the classroom, and the chaos which hung heavy in the air a few moments ago, had slipped into oblivion.

He walked upto his desk in the middle of the dias, stationed his seemingly heavy bag upon it and then put both his hands on his hips and surveyed the room thoroughly, with his eyes looking over the
reading glasses, which hung way down the bridge of his nose. He seemed to mildly shake his head and give out a long sigh, as if contemplating if this was the life he had envisioned for himself. Then,
with almost a hint of despair, he fished out the attendance register from his bag and set upon the tedious task of recording the students' presence, alteast in the physical sense. I went back to my
caricatures since I knew my roll number wouldn't be due soon as Mr. Pandey started calling out the roll numbers and names with a lethargic monotony in his voice.

It went along fine for a while.

"1124. Gurusimran Singh"

There was a hushed silence again but this time it seemed pregnant with the promise of an imminent commotion. When I lifted my eyes from my pages and looked around, some people in the front had turned
backwards, craning their neck, as if expectantly waiting for something to unfold. There was some muffled discussion going on between two boys, seated two rows beyond me.

Mr. Pandey looked up from his register and called out with greater authority: "1124. Gurusimran Singh?"

Instantly a hand popped up this time, followed by a call in strong voice: "Present!". The tone was loud and confidant enough to have quelled any doubts of mischief but Mr.Pandey had detected that
something was amiss, as he stood with his square head slightly tilted to one side, his eyes perched on that small bracket in the back of the class from where the sound had emerged.

"Kaun hai, Khada ho toh zara jee?"
("Whoever it is, please stand up?")

After some deliberation, the body associated with that confident hand did seem to straighten up and emerge from the bowels of anonymity as every eye in the room was completely focussed on him.
Mr.Pandey gave him a thorough once over, and then remarked:

"Aap hi hain...Guru..Simran..Singh?", he said while bobbing his head in a strange manner for every component of the name.
(Are you Guru Simran Singh?)

The reply was instant.

"Yes"

"Hum soche aap punjabi honge (I thought you would be a Punjabi/Sikh)", he said creating a mock expression of wonder on his face.

"Punjabi hi hain sir, pagdi wala nahi bas (I am a Punjabi Sir, but not the turbaned one)", he said in his unmistakably curious Hindi dialect and as soon as he said this, as if on a cue, whole of the
room burst into a laughter while Mr.Pandey developed a smirk on his face. But when this episode was unfolding, something quite different had caught my eye and the din and rapture all around me didn't
totally register with me for the next few moments.

It was this girl, seated in the second row from the front, who was half-turned towards the back, effusing a sparkling smile while her partially closed palms rested below her chin, almost adding a
royal elegance to that posture of hers. It might have been a reticent giggle or an opulent smile, but there was something about it that left me mesmerized, as if urging me from the inside to somehow
recreate this sorcery on paper. Let me be clear, it didn't ask, in fact it demanded of me, in a way even tried to challenge me to dare to put that image onto paper, which had by now become etched in
the back of my head.

My gaze was still affixed on her as the classroom had now recovered from their bouts of laughter, and the air autmatically felt lighter and fresher as if having a chuckle had sort of mellowed down the
atmosphere a bit and had warded off all signs of drowsiness as was the case with morning classes. Mr. Pandey was now addressing the whole class, narrating another of his anecdotes, but his voice
sounded muffled to me, as if flowing in from a distant dream.

I was still looking at her, while she retreated to her normal position, every inch of her turn executed with perfect grace. I am not sure, but something told me she had felt the heaviness of my stare
upon her, and not to sound deluded but I think I did notice her moving her neck slightly sideways a few seconds later, perhaps trying to catch a glimpse of her ogler. When several years later, I asked her
whether she did see me staring at her that day, she said with a hint of hesitation that she did not have a clear recollection of that day and thus could not affirm my claims.

The shrill bell brought an end to the reign of Mr.Pandey and brought back the familiar unrest to the room, while I sat there wondering if something deep within me had changed forever. It was as if the
pieces of my being had been taken apart, shuffled and rearranged in a more harmonic manner as I couldn't yet wash off that portrait of hers off my mind. For the next few lectures, I ordained myself
to try and recreate the image again on paper in order to restore the sanity of my brain, so my memory of the rest of the day is quite cloudy and all I remember doing is sketching her with a manic
obsession. 

Even she did acknowledge it later that it was that portrait, which had tugged at her heart and had consequently generated some sort of interest in me on her part. Even after we drifted apart later, as
life would have it, I never could bring myself to getting rid of that particular sketch. I still remember that when I was systematically getting rid of all the things around me that reminded me of her
and the time we spent together, I found it neatly folded and tucked inside one of my ancient notebooks. I opened it and stole a quick glance at it, strangely I felt neither rage nor remonstration at
the sight of it for it wasn't really a souvenir of a failed relationship for me. It was more like a sweet reminder of a different world, wherein I had successfully attempted to hold on to this gentle
strand of space and time forever projecting the ageless and immortal reflection of that smiling 21 year old girl.


---------

I didn’t think I would ever fall in love again. I know that everyone says that after a heartbreak, but the difference is that I’m not heartbroken. I’m not cynical, or pessimistic, or sad. I’m just
someone who once felt something bigger than anything else I’d ever felt and when I lost it, I honestly believed I would never have that again. But... I was 22 then and life is long. And I’m feeling
things right now that I haven’t in a long, long time. Its a thought that keeps riling my conscience, making me believe that I could have all that again, everything that I had lost.

Meera was shuffling through the heaps of papers and notebooks piled chaotically on the shelves, with a hand above her nose to protect herself from the cloud of dust rising everytime she would move
anything around. She hated all forms of entropy and felt all things in the universe, big and small, should be assembled in a predefined order and kept waging wars in various facets of her life towards
this specific cause. You could see that reflected in her desk at the office, her flat and even in her future plans for herself. Perhaps you could say that sometimes I was the only anomaly sometimes
lurking in her vicinity, in the otherwise orb of perfect sequence and structure surrounding her.

"When did you last use anything from up here?", she said pointing at the dusty shelf, her hand still covering her nose.

I just shrugged, which did mildly irritate her for she was there, in my room, bringing a much needed organizational change and I seemed to be offering absolutely nothing.

"I am just going to arrange all these into your 'rarely' used dustbin for now", she remarked in a somewhat sarcastic tone.

As she was moving the pile of sheets and notebooks, a rebellious leaf of paper glided off the stack and gently settled on the floor, capturing immediate attention of both the occupants of the room.
Except, to me, it felt quite odd to look at that again, that token from a previous life which now did seem like an elaborate dream.
  
"Who is this girl? Do I need to feel threatened?", she said squinting her eyes and fiegning a stern expression on her face.

"Threatened of her? No, you shouldn't be."

"Also I think she is far away in the United States right now, partly the reason I had to settle on you", I added with a mischievous grin.

"Yeah right, such was your effect on her that she had to elope across the oceans. I wouldn't even have the means to leave this city, and also when it does come to that I think you should be the one
leaving the job and fleeing away, given that Raghav and anyone else in office would side with me."

I couldn't help but let out a restrained chuckle.

"Raghav is anyways smitten by your charm. Also the girl is from way down the alleys of my past, and it was just one of those benign college love affairs."

'Oh is it? Then may I ask, why this sketch, which is brilliant by the way, preserved in your shelf like a relic', she retorted, with her mock interest now transforming into genuine curiousity.
 
I just shook my head and said: "It was never meant to be preserved, rather somthing which was not consciously discarded, just like the other piles of useless sheets you might see there."

"Doesn't seem useless to me", she said and noticed in my eyes that I had drifted elsewhere.  

"Also, when are you making a portrait for me? Given that you are so awful at clicking pictures of me you do owe me that in the least."

"I am a bit rusty but then again you shouldn't mind if I mess up your nose or your lips. I will get my notebook, you just need to manage to stay still for a while", I said with a smile.

"I didn't mean now! Also I need to get back by 9, otherwise mom would scream her throat off at me", she said and stole a glance at her watch.

"Yeah, yeah we would have ample time. Atleast I am not going anywhere."

"Yup, all thanks to that home loan of yours", she quipped, as she hurriedly picked up her stuff and started to advance towards the door.

"Hey wait, what are we doing tomorrow? Are you coming down?", I called out to her as she scuttled to the door and unlocked it.

She stopped in her stride, turned around and flashed this glittering smile at me. With her hair falling over her face and her eyebrows slightly arched over her big beautiful eyes, she stood there for
a while beaming at me, as time once again, froze for me in strict sense of 'Deja Vu'. 

"Not until I get that portrait of mine", she said before rushing out of the door and shutting it behind her.

The reverie was shattered by the sound of the door but those words of hers kept ringing in my ear. I got up lazily, picked up that sheet off the ground, and with almost a stoic sense of diligence made
a paper plane out of it before launching it towards the dustbin.

It glided majestically for a while before falling well short of its destination.
